# not the best way to do this, but i was gonna add properties with each account, but then I removed that
gbrInstances:
  - id: 0
  - id: 1
  - id: 2
  - id: 3
  - id: 4
  - id: 5
  - id: 6
  - id: 7
  - id: 8