{{- range $i, $s := (.Values.gbrInstances) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbr-{{ $i }}
  labels:
    app: gbr-{{ $i }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gbr-{{ $i }}
  template:
    metadata:
      labels:
        app: gbr-{{ $i }}
    spec:
      containers:
      - name: gbr-{{ $i }}
        image: 833642098503.dkr.ecr.us-east-2.amazonaws.com/gbr-containers:latest
        env:
        - name: GBR_ACCOUNT_USERNAME
          value: '{{ .username }}'
        - name: GBR_ACCOUNT_PASSWORD
          value: '{{ .password }}'
        - name: GBR_ACCOUNT_RANK
          value: '{{ .rank }}'
        ports:
        - name: "p9222"
          containerPort: 9222
        - name: "p3001"
          containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: gbr-service-{{ $i }}
spec:
  selector:
    app: gbr-{{ $i }}
  ports:
    - name: "p9222"
      protocol: TCP
      port: 9222
      targetPort: 9222
    - name: "p3000"
      protocol: TCP
      port: 3001
      targetPort: 3001
{{- end }}