apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbstats
  labels:
    app: gbstats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gbstats
  template:
    metadata:
      labels:
        app: gbstats
    spec:
      # https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html 
      serviceAccountName: gbr-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                    - gbdist
                    - mongodb
                    - gbsource
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: gbstats
        image: 833642098503.dkr.ecr.us-east-2.amazonaws.com/gbstats-containers:latest
        # env:
        #   - name: GBR_INSTANCE_COUNT
        #     value: '{{ len .Values.gbrInstances }}'
        ports:
        - name: "p3000"
          containerPort: 3000
        volumeMounts:
          - mountPath: /usr/src/app/config
            name: config-secret
      volumes:
        - name: config-secret
          secret:
            secretName: config-secret
            items:
            - key: config.json
              path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: gbstats-service
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    # Backend talks over http and ws protocols so 'http' cannot be used because it does not allow ws upgrade.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    # Non-sensitive information. Replace with your own cert arn if running your own instance
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:833642098503:certificate/ab6018f0-5684-4a8d-bcc4-985350760284
    # Only run SSL (Secure TCP) on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"

    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: stickiness.enabled=true,preserve_client_ip.enabled=true,proxy_protocol_v2.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  labels:
    app: gbstats
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: https
    port: 443
    targetPort: 3000
  selector:
    app: gbstats
