apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                    - gbdist
                    - gbstats
                    - gbsource
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - name: "p27017"
          containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: '{{ .Values.db.username }}'
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: '{{ .Values.db.password }}'
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: "p27017"
      protocol: TCP
      port: 27017
      targetPort: 27017
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: mongo-client
#   name: mongo-client
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mongo-client
#   strategy: {}
#   template:
#     metadata:
#       labels:
#         app: mongo-client
#     spec:
#       containers:
#       - image: mongoclient/mongoclient
#         name: mongo-client
# # mongo --host mongodb-service.mongodb --port 27017 -u usernamee -p passwordd
