apiVersion: v1
kind: Secret
metadata:
  name: accounts-secret
type: Opaque
stringData:
  accounts_json: |
    [
        { "username":"account@name.email", "password":"accountpassword", "rank":111},
    ]
